# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('samples-routing', ['core','network'])
    module.source = [
        'model/samples-routing.cc',
        'helper/samples-routing-helper.cc',
        'model/samples-routing-app.cc',
        'model/samples-routing-channel.cc',
        'model/samples-routing-net-device.cc',
        'model/samples-routing-packet.cc',
        'model/samples-routing-queue.cc',
        'model/samples-routing-router.cc',
        'model/samples-routing-node.cc',
        ]

    module_test = bld.create_ns3_module_test_library('samples-routing')
    module_test.source = [
        'test/samples-routing-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/samples-routing-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'samples-routing'
    headers.source = [
        'model/samples-routing.h',
        'helper/samples-routing-helper.h',
        'model/samples-routing-app.h',
        'model/samples-routing-channel.h',
        'model/samples-routing-net-device.h',
        'model/samples-routing-packet.h',
        'model/samples-routing-queue.h',
        'model/samples-routing-router.h',
        'model/samples-routing-node.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

